FROM flink:1.17-scala_2.12

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install apache-flink==1.17.2

WORKDIR /app

COPY src/ /app/src/
COPY jars/ /app/jars/