name: "Tworzenie Issue z TODO"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Krytyczne: pozwala botowi na tworzenie zadań
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
        with:
          INSERT_ISSUE_URLS: "true" # Dopisuje link do issue w kodzie